services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSocket
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    user: "1883:1883"
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./influxdb/influxdb-config.yml:/etc/influxdb2/config.yml
    user: "1000:1000"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=7d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    restart: unless-stopped

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    user: "999:999"
    env_file:
      - .env
    restart: unless-stopped

  nodered:
    build: ./nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered-data:/data
      # Add source directory for live development
      - ./nodered:/data/nodes
    user: "1000:1000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mosquitto
      - influxdb
      - postgres
    restart: unless-stopped

  webapp:
    build: ./webapp
    ports:
      - "80:5000"
    volumes:
      - ./webapp:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SERVER_IP=192.168.1.100
    depends_on:
      - postgres
    restart: unless-stopped

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-klokkeprosjekt}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
      - postgres
    restart: unless-stopped

volumes:
  influxdb-data:
    driver: local
  postgres-data:
    driver: local
  nodered-data:
    driver: local
  grafana-data:
    driver: local
