FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# Add debug script
RUN echo "#!/bin/sh\nenv\npython app.py" > /app/start.sh
RUN chmod +x /app/start.sh

CMD ["/app/start.sh"]
